# Generated by Django 4.2.1 on 2023-05-22 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type of exception', max_length=50)),
                ('url', models.CharField(help_text='Url endpoint', max_length=50)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(help_text='Type of http method', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response', models.TextField(help_text='Error log')),
                ('description', models.TextField(help_text='Reason of error')),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('content_type', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
