from django.conf import settings

ISSUE_TRACKER_CHANNELS_CONFIGURATION = settings.ISSUE_TRACKER_CHANNELS_CONFIGURATION
EMAIL_ADMIN_USER = settings.EMAIL_ADMIN_USER
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
