# Generated by Django 4.2.1 on 2023-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type of exception', max_length=64)),
                ('description', models.TextField(help_text='Reason of error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='Additional data')),
            ],
        ),
    ]
